import SwiftUI

/// The Focus Quest brand mascot — a cute tomato-spirit. Art is generated by the
/// Codex gpt-image pipeline (scripts/gen_mascot.sh) into Assets.xcassets/mascot/
/// as frames (idle / wave / celebrate); this view animates them procedurally with
/// TimelineView so the motion stays smooth and stateless.
struct MascotView: View {
    enum MascotState { case idle, wave, celebrate }

    var state: MascotState = .idle
    var size: CGFloat = 120

    @State private var start = Date()

    var body: some View {
        TimelineView(.animation) { tl in
            let t = tl.date.timeIntervalSince(start)
            let s = sample(at: t)
            frameImage(s.frame)
                .frame(width: size, height: size)
                .scaleEffect(x: s.scaleX, y: s.scaleY, anchor: .bottom)
                .rotationEffect(.degrees(s.rot))
                .offset(y: s.dy)
        }
    }

    private func sample(at t: Double) -> (frame: String, dy: CGFloat, rot: Double, scaleX: CGFloat, scaleY: CGFloat) {
        switch state {
        case .idle:
            let breath = sin(t * 2 * .pi / 2.6)
            return ("mascot_idle", breath * -1.5, breath * 1.2, 1, 1 + breath * 0.03)
        case .wave:
            // Alternate idle/wave for a hand-waving feel, with a gentle tilt.
            let frame = Int(t / 0.45).isMultiple(of: 2) ? "mascot_wave" : "mascot_idle"
            return (frame, 0, sin(t * 2 * .pi / 0.9) * 4, 1, 1)
        case .celebrate:
            let bounce = abs(sin(t * 2 * .pi / 0.5))
            return ("mascot_celebrate", -bounce * size * 0.06, sin(t * 2 * .pi / 0.42) * 3, 1, 1 + bounce * 0.05)
        }
    }

    private func frameImage(_ name: String) -> some View {
        Group {
            if AssetLookup.exists(name) {
                Image(name).resizable().interpolation(.high).aspectRatio(contentMode: .fit)
            } else if AssetLookup.exists("mascot_idle") {
                Image("mascot_idle").resizable().interpolation(.high).aspectRatio(contentMode: .fit)
            } else {
                // Vector fallback if the generated art is missing.
                ZStack {
                    Circle().fill(LinearGradient(colors: [Theme.accent, Color(hex: 0xE0334D)],
                                                 startPoint: .top, endPoint: .bottom))
                    Image(systemName: "leaf.fill").foregroundStyle(Theme.mint)
                        .offset(y: -size * 0.42).font(.system(size: size * 0.22))
                }
            }
        }
    }
}

#Preview {
    HStack(spacing: 24) {
        MascotView(state: .idle, size: 120)
        MascotView(state: .wave, size: 120)
        MascotView(state: .celebrate, size: 120)
    }
    .padding(40)
    .background(Theme.bg)
}
